version: "3.8"
services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: salihasoyturk
            MONGO_INITDB_ROOT_PASSWORD: ankageo
        ports:
            - 27017:27017
        volumes:
            - ./database-data:/data/db

    # Mongo Express Service for GUI purpose.
    mongo-express:
        image: mongo-express:latest # latest image
        container_name: mongo-express
        restart: unless-stopped
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: salihasoyturk
            ME_CONFIG_MONGODB_ADMINPASSWORD: ankageo
            ME_CONFIG_MONGODB_SERVER: mongodb
        depends_on:
            - mongodb